slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom               # Frame odometry từ plugin MecanumDrive
    map_frame: map                 # Frame bản đồ gốc
    base_frame: robot_base_footprint # ĐÃ SỬA: Phải có chữ "robot_" cho khớp URDF
    scan_topic: /scan              # Topic LiDAR của MAINBOT
    use_sim_time: true             # Bắt buộc bật cho Gazebo Harmonic

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_region_strategy: LEVENBERG_MARQUARDT # ĐÃ SỬA TYPO (thêm chữ _region_)
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Lập bản đồ
    mode: mapping                  
    resolution: 0.05               # Độ phân giải bản đồ: 5cm / 1 pixel
    map_update_interval: 5.0
    transform_publish_period: 0.02 # Cập nhật TF map->odom ở tốc độ 50Hz
    
    # Cấu hình quét và ma trận
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    scan_buffer_size: 10
    max_laser_range: 10.0          # Khớp với tầm nhìn 10.0m của MAINBOT
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true